### PR TITLE
Rename Ledger::settings to settings_mut and add settings getter

### PR DESCRIPTION
**Pull request by CodeSandwich**
Part of https://github.com/input-output-hk/jormungandr/issues/1137

This is technically a breaking change, but it breaks no code in chain-libs or Jormungandr.

### CODE REVIEW

**Comment by NicolasDP** [comment]
While I appreciate the API change. I am not sure that exposing the settings is still a good thing. Everything has been done, so far, to not expose these values as they have meaning that are not meant to be shared.

For working on #input-output-hk/jormungandr#1137 you need to use only the `LeaderParameters`. They are the only valid values worth using. And you can only get it from the appropriate `tip`.

**Comment by CodeSandwich** [comment]
It turns out that `Ledger::settings()` isn't used anywhere anymore. I've removed it completely.

**Comment by NicolasDP** [comment]
Thanks. I think this is going toward the right direction. However, there is also a reason why this value was not exposed in the first place: we are not sure sure how to enforce it just yet. Here we are counting in number of transactions, but we want to count in number of fragments per block.

Also:

* this value is not checked by the ledger at the moment;
* all fragments are not equals, some have 255 inputs and 255 outputs for example, Would it not be better to have a limit in byte size instead?

**Comment by CodeSandwich** [comment]
I'm going to close this PR, it makes no sense to push this functionality any more, it's broken and slated for replacement

**Pull request closed without merging**
