### PR TITLE
Starting removing ed25519 bip32 for direct use

### PR DESCRIPTION
**Pull request by vincenthz**
* move towards requiring only public interface in chain implementation
* ed25519 public key are all the same

### CODE REVIEW

**Comment by SebastienGllmt** [comment]
Is it possible that you please not merge this until after the first release of Shelley this month? Otherwise if you make any last-second breaking changes we won't be able to update our fork of chain-libs without ugly merge conflicts that we don't have time to deal with right now 🙏

**Comment by vincenthz** [comment]
I can indeed old off for a bit, but the only right option is to move to the provider of xprv/xpub for any generation/derivation related business (ed25519-bip32 package) and only deal in term of ed25519 signature and public keys which have absolutely no bearing on whether or not they are normal ed25519, extended ed25519 or xprv.

**Comment by vincenthz** [comment]
btw, without a serious plan to either merge back and have a path forward though, this will be a useless wait.

**Comment by SebastienGllmt** [comment]
Yes I will deal with whatever changes need to be made after the release goes out. At that point you can merge this PR and we will make it work.

**Comment by SebastienGllmt** [comment]
You can merge this now if you want to since we have time to deal with re-adding this on our end

**Comment by vincenthz** [comment]
fix #258

**Pull request merged**
