### PR TITLE
remove GH Actions reduntant runs

### PR DESCRIPTION
**Pull request by eugene-babichenko**
Tests are run on every push so there is no need to trigger them again
when opening a pull request.

### CODE REVIEW

**Comment by mzabaluev** [comment]
OK if it's really redundant. I recall Travis checked out a pre-merged tree to build for pull request so the result might be different there.

**Comment by eugene-babichenko** [comment]
@mzabaluev hm, seems you're right. I checked `actions/checkout@v1`, here is an example:

`git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/pull/371/merge:refs/remotes/pull/371/merge`.

In that case the question is whether there is a need to run the `push` trigger for **every** branch even if it is not a part of a pull request?

**Comment by mzabaluev** [comment]
If `pull_request` rebuilds on (force-)pushes after the initial PR has been created, then `push` for bare branches is redundant.

**Comment by eugene-babichenko** [comment]
@mzabaluev I was experimenting in this pull request https://github.com/input-output-hk/jorup/pull/16. `pull_request` is triggered every time there is a push to this pull request.

**Pull request merged**
