### PR TITLE
run cargo fmt &clippy 1.51

### PR DESCRIPTION
**Pull request by eugene-babichenko**

### CODE REVIEW

**Review by Zeegomo — COMMENTED** [review]
There is a failing lint related to `imhamt`, otherwise looks good.

**Comment by eugene-babichenko** [comment]
Yup, there are still things to be fixed.

**Review by mzabaluev — APPROVED** [review]
Looks good, will cause a massive update in jormungandr though.

**Comment by eugene-babichenko** [comment]
Not only in `jormungandr` and this is why I suggested to disable the `upper-case-acronyms` lint.

**Comment by eugene-babichenko** [comment]
no red x

**Pull request merged**
